export interface CaseStudy {
  id: string;
  sector: string;
  sectorId: string;
  title: string;
  client: string;
  challenge: string;
  solution: string;
  result: string;
  brands: string[];
  tags: string[];
}

export const SECTORS = [
  { id: 'all', label: 'All Sectors' },
  { id: 'residential-homes', label: 'Residential Homes' },
  { id: 'bungalows-villas', label: 'Bungalows & Villas' },
  { id: 'hotels-hospitality', label: 'Hotels & Hospitality' },
  { id: 'hospitals-healthcare', label: 'Hospitals & Healthcare' },
  { id: 'educational-institutions', label: 'Educational Institutions' },
  { id: 'industrial-manufacturing', label: 'Industrial & Manufacturing' },
  { id: 'retail-commercial', label: 'Retail & Commercial' },
  { id: 'housing-societies', label: 'Housing Societies' },
  { id: 'restaurants-food', label: 'Restaurants & Food' },
  { id: 'farmhouses-agricultural', label: 'Farmhouses & Agricultural' },
] as const;

export const caseStudies: CaseStudy[] = [
  // ─── Residential Homes ────────────────────────────────────────────────────
  {
    id: 'rh-01',
    sector: 'Residential Homes',
    sectorId: 'residential-homes',
    title: '5 kW Rooftop Solar System for Independent House',
    client: 'Private homeowner, Pune',
    challenge: 'Monthly electricity bills of ₹4,500+ with frequent load-shedding affecting home appliances.',
    solution: 'Designed and installed a 5 kW on-grid solar system with net metering on a south-facing roof.',
    result: '80% reduction in electricity bills, grid credits earned during peak generation hours.',
    brands: ['V-Guard'],
    tags: ['Solar', 'On-Grid', 'Net Metering'],
  },
  {
    id: 'rh-02',
    sector: 'Residential Homes',
    sectorId: 'residential-homes',
    title: 'Heat Pump Water Heater Replacement',
    client: 'Family of 5, Nashik',
    challenge: 'Old 25-litre electric geyser failing to meet daily hot water demand and consuming excessive power.',
    solution: 'Replaced with a V-Guard 200-litre heat pump water heater with smart temperature control.',
    result: '70% energy savings versus the old geyser; consistent hot water for entire family.',
    brands: ['V-Guard'],
    tags: ['Water Heating', 'Heat Pump', 'Energy Saving'],
  },
  {
    id: 'rh-03',
    sector: 'Residential Homes',
    sectorId: 'residential-homes',
    title: 'Whole-House RO Drinking Water System',
    client: 'Residential bungalow, Aurangabad',
    challenge: 'High TDS ground water causing scale deposits and health concerns for the family.',
    solution: 'Installed a Zero B under-sink RO purifier with a UV stage for microbial safety.',
    result: 'TDS reduced from 780 ppm to under 50 ppm; zero scale buildup reported after 12 months.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'RO', 'Drinking Water'],
  },
  {
    id: 'rh-04',
    sector: 'Residential Homes',
    sectorId: 'residential-homes',
    title: 'Pressure Booster Pump for Low-Rise Home',
    client: 'Ground-floor flat, Nagpur',
    challenge: 'Insufficient water pressure at kitchen and bathroom fixtures due to a low-lying overhead tank.',
    solution: 'Installed a Wilo pressure booster pump with pressure switch for automatic operation.',
    result: 'Consistent 2.5 bar pressure achieved; all fixtures operating normally without manual intervention.',
    brands: ['Wilo'],
    tags: ['Pumping', 'Pressure Booster', 'Residential'],
  },

  // ─── Bungalows & Villas ───────────────────────────────────────────────────
  {
    id: 'bv-01',
    sector: 'Bungalows & Villas',
    sectorId: 'bungalows-villas',
    title: '10 kW Solar System for Luxury Villa',
    client: 'Private villa owner, Lonavala',
    challenge: 'High energy costs from air conditioning, pool pump, and home automation equipment.',
    solution: 'Installed a 10 kW on-grid rooftop solar system with monitoring app integration.',
    result: '₹8,000+ monthly savings; system paid back in under 4 years at current tariffs.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Luxury', 'High Capacity'],
  },
  {
    id: 'bv-02',
    sector: 'Bungalows & Villas',
    sectorId: 'bungalows-villas',
    title: 'Heat Pump + Water Softener Package',
    client: 'Weekend villa, Mahabaleshwar',
    challenge: 'Hard water causing scale in heaters and pipes; inadequate hot water for multiple bathrooms.',
    solution: 'Installed a 300-litre V-Guard heat pump and a Zero B water softener at the point of entry.',
    result: 'Scale eliminated across plumbing; heat pump delivering hot water for 4 bathrooms simultaneously.',
    brands: ['V-Guard', 'Zero B'],
    tags: ['Water Heating', 'Water Softening', 'Combo Solution'],
  },
  {
    id: 'bv-03',
    sector: 'Bungalows & Villas',
    sectorId: 'bungalows-villas',
    title: 'Solar Water Heater for Farm Villa',
    client: 'Farm bungalow, Nashik outskirts',
    challenge: 'No reliable grid power for electric geyser in a rural villa with abundant sunlight.',
    solution: 'Installed a 200-litre V-Guard solar water heater with electric backup element.',
    result: 'Hot water available 10 months of the year from solar alone; backup kicks in only on overcast days.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Water Heating', 'Rural'],
  },

  // ─── Hotels & Hospitality ─────────────────────────────────────────────────
  {
    id: 'hh-01',
    sector: 'Hotels & Hospitality',
    sectorId: 'hotels-hospitality',
    title: '50 kW Rooftop Solar for Mid-Scale Hotel',
    client: '45-room business hotel, Pune',
    challenge: 'Rising electricity costs eating into hotel margins; diesel generator dependency during load-shedding.',
    solution: 'Deployed a 50 kW on-grid solar system across the flat rooftop.',
    result: '40% reduction in grid electricity draw; diesel generator usage dropped by 90%.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Commercial', 'Large Scale'],
  },
  {
    id: 'hh-02',
    sector: 'Hotels & Hospitality',
    sectorId: 'hotels-hospitality',
    title: 'Centralised Heat Pump for 60-Room Resort',
    client: 'Hill station resort, Mahabaleshwar',
    challenge: 'Electric boilers failing to handle peak morning hot water demand for 60 rooms.',
    solution: 'Replaced boilers with three linked V-Guard commercial heat pumps (500 L each) in cascade configuration.',
    result: 'Consistent 60°C supply; 65% energy saving versus old boilers; zero morning pressure complaints.',
    brands: ['V-Guard'],
    tags: ['Water Heating', 'Heat Pump', 'Hospitality'],
  },
  {
    id: 'hh-03',
    sector: 'Hotels & Hospitality',
    sectorId: 'hotels-hospitality',
    title: 'High-Rise Hotel Booster Pump System',
    client: '8-floor hotel, Aurangabad',
    challenge: 'Upper floors experiencing severely low water pressure, leading to guest complaints.',
    solution: 'Installed a Wilo multi-stage inline booster pump with variable frequency drive for consistent pressure.',
    result: 'Uniform 3.5 bar pressure on all floors; energy use reduced through VFD speed control.',
    brands: ['Wilo'],
    tags: ['Pumping', 'Booster', 'High-Rise'],
  },
  {
    id: 'hh-04',
    sector: 'Hotels & Hospitality',
    sectorId: 'hotels-hospitality',
    title: 'RO Water Treatment for Hotel Kitchen & Bar',
    client: 'Boutique hotel, Nashik wine region',
    challenge: 'Mineral-rich bore water affecting food and beverage quality and causing equipment scaling.',
    solution: 'Installed a Zero B commercial RO system with pre-filtration and UV polishing stage.',
    result: 'Purified water across kitchen and bar; ice machines running scale-free for over 18 months.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'RO', 'Commercial'],
  },

  // ─── Hospitals & Healthcare ───────────────────────────────────────────────
  {
    id: 'hc-01',
    sector: 'Hospitals & Healthcare',
    sectorId: 'hospitals-healthcare',
    title: '30 kW Solar for Multispeciality Clinic',
    client: 'Multispeciality clinic, Nagpur',
    challenge: 'High AC and medical equipment loads causing monthly bills exceeding ₹80,000.',
    solution: 'Installed a 30 kW on-grid solar system with net metering on the hospital rooftop.',
    result: 'Monthly bill reduced to ₹28,000; carbon footprint reduced by ~25 tonnes/year.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Healthcare', 'Large Scale'],
  },
  {
    id: 'hc-02',
    sector: 'Hospitals & Healthcare',
    sectorId: 'hospitals-healthcare',
    title: 'Commercial Heat Pump for Patient Ward Hot Water',
    client: 'District hospital, Jalgaon',
    challenge: 'Aging electric boiler unreliable for providing hot water to 120-bed ward round the clock.',
    solution: 'Replaced with dual V-Guard commercial heat pumps, 500 L each, with auto-failover.',
    result: 'Uninterrupted 24/7 hot water; maintenance calls eliminated in the first year of operation.',
    brands: ['V-Guard'],
    tags: ['Water Heating', 'Healthcare', 'Heat Pump'],
  },
  {
    id: 'hc-03',
    sector: 'Hospitals & Healthcare',
    sectorId: 'hospitals-healthcare',
    title: 'Zero B RO Purification for Hospital Dialysis Unit',
    client: 'Nephrology hospital, Pune',
    challenge: 'Dialysis machines requiring pharmaceutical-grade water; existing RO not meeting TDS standards.',
    solution: 'Installed a Zero B multi-pass RO system with double deionisation and real-time TDS monitoring.',
    result: 'Water quality consistently below 10 ppm TDS, exceeding AAMI standards for dialysis use.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'RO', 'Medical Grade'],
  },

  // ─── Educational Institutions ─────────────────────────────────────────────
  {
    id: 'ei-01',
    sector: 'Educational Institutions',
    sectorId: 'educational-institutions',
    title: '20 kW Solar for Engineering College',
    client: 'Private engineering college, Pune',
    challenge: 'High electricity costs for computer labs and HVAC running 12 hours daily.',
    solution: 'Installed a 20 kW on-grid solar array on the academic block roof.',
    result: '₹1.2 lakh annual saving; also used as live demonstration for electrical engineering students.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Education', 'On-Grid'],
  },
  {
    id: 'ei-02',
    sector: 'Educational Institutions',
    sectorId: 'educational-institutions',
    title: 'Solar Water Heater for Residential Hostel',
    client: '200-student hostel, Nashik',
    challenge: 'Electric geysers unable to supply hot water for 200 students in morning peak hours.',
    solution: 'Installed four 500-litre V-Guard solar water heaters on the hostel roof with a common distribution header.',
    result: 'Adequate hot water for all students by 6:30 AM; 75% reduction in water-heating electricity costs.',
    brands: ['V-Guard'],
    tags: ['Water Heating', 'Solar', 'Hostel'],
  },
  {
    id: 'ei-03',
    sector: 'Educational Institutions',
    sectorId: 'educational-institutions',
    title: 'Water Softener for School Drinking Water System',
    client: 'CBSE school, Aurangabad',
    challenge: 'Hard bore water damaging RO membranes frequently and causing scaling in drinking water dispensers.',
    solution: 'Installed a Zero B central water softener as pre-treatment before the existing RO systems.',
    result: 'RO membrane life extended from 6 months to 24+ months; no scaling reported in dispensers.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'Softening', 'Education'],
  },

  // ─── Industrial & Manufacturing ───────────────────────────────────────────
  {
    id: 'im-01',
    sector: 'Industrial & Manufacturing',
    sectorId: 'industrial-manufacturing',
    title: '100 kW Solar for Steel Fabrication Unit',
    client: 'Steel fabrication plant, Nagpur',
    challenge: 'Power-intensive welding and CNC machines driving monthly electricity bills above ₹2 lakh.',
    solution: 'Installed a 100 kW on-grid solar system with industrial metering across the factory roof.',
    result: '55% electricity offset achieved; annual saving of ₹13 lakh at current industrial tariffs.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Industrial', 'Large Scale'],
  },
  {
    id: 'im-02',
    sector: 'Industrial & Manufacturing',
    sectorId: 'industrial-manufacturing',
    title: 'Wilo Booster Pumps for Multi-Building Factory',
    client: 'Textile processing unit, Bhiwandi',
    challenge: 'Inadequate water pressure across three production buildings from a single overhead tank.',
    solution: 'Installed three Wilo booster pump sets, one per building, with centralised pressure monitoring.',
    result: 'Consistent 4 bar pressure across all processing lines; production downtime due to water pressure eliminated.',
    brands: ['Wilo'],
    tags: ['Pumping', 'Industrial', 'Multi-Building'],
  },
  {
    id: 'im-03',
    sector: 'Industrial & Manufacturing',
    sectorId: 'industrial-manufacturing',
    title: 'Industrial Water Treatment for Food Packaging Facility',
    client: 'Food packaging plant, Pune',
    challenge: 'Process water TDS and chlorine levels not meeting food safety compliance standards.',
    solution: 'Installed a Zero B industrial RO + activated carbon filtration system sized for 10,000 L/day.',
    result: 'Full FSSAI compliance achieved; zero compliance failures in subsequent audits.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'Compliance', 'Food Industry'],
  },

  // ─── Retail & Commercial Complexes ────────────────────────────────────────
  {
    id: 'rc-01',
    sector: 'Retail & Commercial Complexes',
    sectorId: 'retail-commercial',
    title: '40 kW Solar for Shopping Complex',
    client: 'Community shopping complex, Nashik',
    challenge: 'Shared electricity costs for common lighting and HVAC were a persistent tenant grievance.',
    solution: 'Installed a 40 kW rooftop solar system to offset common-area electricity consumption.',
    result: 'Common area electricity bills cut by 70%; maintenance corpus partially funded by net-metering credits.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Retail', 'Common Area'],
  },
  {
    id: 'rc-02',
    sector: 'Retail & Commercial Complexes',
    sectorId: 'retail-commercial',
    title: 'Pressure Pump System for Multi-Floor Commercial Building',
    client: '6-floor commercial complex, Pune',
    challenge: 'Retail shops on upper floors facing low water pressure, affecting washrooms and pantries.',
    solution: 'Installed a Wilo variable-speed pressure pump with smart pressure controller.',
    result: 'Steady 3 bar pressure on all floors; pump energy consumption reduced 30% via variable speed operation.',
    brands: ['Wilo'],
    tags: ['Pumping', 'Commercial', 'Variable Speed'],
  },
  {
    id: 'rc-03',
    sector: 'Retail & Commercial Complexes',
    sectorId: 'retail-commercial',
    title: 'Centralised RO for Food Court Water Supply',
    client: 'Mall food court, Aurangabad',
    challenge: 'Multiple food stall owners each running small RO units with inconsistent water quality.',
    solution: 'Installed a single Zero B centralised RO system with distribution plumbing to all 12 stalls.',
    result: 'Uniform purified water quality; maintenance simplified to one system; FSSAI inspections passed.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'RO', 'Food Court'],
  },

  // ─── Housing Societies & Apartments ──────────────────────────────────────
  {
    id: 'hs-01',
    sector: 'Housing Societies & Apartments',
    sectorId: 'housing-societies',
    title: '25 kW Common-Area Solar for Gated Society',
    client: '120-flat gated society, Pune',
    challenge: 'High common electricity charges for lifts, pumps, and security lighting burdening residents.',
    solution: 'Installed a 25 kW on-grid solar system on the clubhouse and podium rooftop.',
    result: 'Common area bills reduced by 60%; surplus units exported to grid under net metering.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Housing Society', 'Common Area'],
  },
  {
    id: 'hs-02',
    sector: 'Housing Societies & Apartments',
    sectorId: 'housing-societies',
    title: 'Centralised Heat Pump for 80-Flat Apartment',
    client: 'High-rise apartment, Nashik',
    challenge: 'Individual geysers in 80 flats causing load spikes in the morning and high maintenance calls.',
    solution: 'Installed a centralised V-Guard heat pump system (2000 L/day) with apartment-level distribution.',
    result: 'Individual geyser maintenance eliminated; morning peak demand reduced by 40%.',
    brands: ['V-Guard'],
    tags: ['Water Heating', 'Heat Pump', 'Centralised'],
  },
  {
    id: 'hs-03',
    sector: 'Housing Societies & Apartments',
    sectorId: 'housing-societies',
    title: 'Multi-Zone Booster Pumps for 12-Floor Tower',
    client: 'Residential tower, Nagpur',
    challenge: 'Extreme pressure variation from ground to 12th floor; upper residents unable to use showers.',
    solution: 'Installed zoned Wilo booster pumps (low zone: floors 1–6, high zone: floors 7–12) with common manifold.',
    result: 'Consistent 2.5 bar at every flat; water-related resident complaints dropped to zero.',
    brands: ['Wilo'],
    tags: ['Pumping', 'High-Rise', 'Zoned'],
  },
  {
    id: 'hs-04',
    sector: 'Housing Societies & Apartments',
    sectorId: 'housing-societies',
    title: 'Society-Level Water Softener Installation',
    client: '200-flat society, Aurangabad',
    challenge: 'Hard municipal water causing scale in geysers and washing machines across all flats.',
    solution: 'Installed a Zero B centralised water softener at the underground sump inlet.',
    result: 'Scale complaints from residents ended; average geyser element life extended from 18 months to 5 years.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'Softening', 'Society'],
  },

  // ─── Restaurants & Food Processing ───────────────────────────────────────
  {
    id: 'rf-01',
    sector: 'Restaurants & Food Processing',
    sectorId: 'restaurants-food',
    title: '15 kW Solar for Restaurant Chain Outlet',
    client: 'QSR chain outlet, Pune',
    challenge: 'High kitchen equipment and HVAC loads resulting in peak-hour electricity costs exceeding ₹25,000/month.',
    solution: 'Installed a 15 kW rooftop solar system on the restaurant terrace.',
    result: '45% offset of daytime electricity; ROI achieved in 3.5 years.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Restaurant', 'Commercial'],
  },
  {
    id: 'rf-02',
    sector: 'Restaurants & Food Processing',
    sectorId: 'restaurants-food',
    title: 'RO Purification for Large Catering Kitchen',
    client: 'Catering commissary, Nashik',
    challenge: 'Bore water with high iron content staining food prep surfaces and affecting taste.',
    solution: 'Installed a Zero B iron removal filter + RO system rated for 5,000 L/day catering use.',
    result: 'Iron content below 0.1 mg/L (WHO standard); staining eliminated and water passed taste panel.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'Iron Removal', 'Catering'],
  },
  {
    id: 'rf-03',
    sector: 'Restaurants & Food Processing',
    sectorId: 'restaurants-food',
    title: 'Booster Pump for Food Processing Plant',
    client: 'Spice processing unit, Nagpur',
    challenge: 'Inconsistent water flow during washing and cooking operations slowing down production line.',
    solution: 'Installed a Wilo inline booster pump with a pressure vessel for surge-free constant flow.',
    result: 'Production line water stoppages eliminated; throughput increased by 15%.',
    brands: ['Wilo'],
    tags: ['Pumping', 'Food Processing', 'Production Line'],
  },

  // ─── Farmhouses & Agricultural ────────────────────────────────────────────
  {
    id: 'fa-01',
    sector: 'Farmhouses & Agricultural',
    sectorId: 'farmhouses-agricultural',
    title: '7.5 kW Solar Pump System for Irrigation',
    client: 'Mango orchard, Ratnagiri',
    challenge: 'Diesel pump costs of ₹12,000/month for drip irrigation; grid power unreliable.',
    solution: 'Replaced diesel pump with a V-Guard solar-powered submersible pump system.',
    result: 'Diesel cost eliminated; irrigation runs automatically during daylight hours.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Agricultural', 'Irrigation'],
  },
  {
    id: 'fa-02',
    sector: 'Farmhouses & Agricultural',
    sectorId: 'farmhouses-agricultural',
    title: 'Solar Water Heater for Farm Worker Accommodation',
    client: 'Agri-tourism farm, Pune district',
    challenge: 'No grid connection at worker dormitory; electric geysers unfeasible.',
    solution: 'Installed three 200-litre V-Guard solar water heaters to serve 30 farm workers.',
    result: 'Full hot water coverage without any grid draw; installation running maintenance-free for 2+ years.',
    brands: ['V-Guard'],
    tags: ['Solar', 'Water Heating', 'Off-Grid'],
  },
  {
    id: 'fa-03',
    sector: 'Farmhouses & Agricultural',
    sectorId: 'farmhouses-agricultural',
    title: 'Bore Water Treatment for Farm Drinking Supply',
    client: 'Farmhouse community, Ahmednagar',
    challenge: 'High TDS and fluoride levels in bore water posing health risks to farm families.',
    solution: 'Installed a Zero B RO system with defluoridation cartridge and UV stage.',
    result: 'Fluoride reduced from 3.2 mg/L to 0.6 mg/L; TDS under 150 ppm; safe drinking water confirmed.',
    brands: ['Zero B'],
    tags: ['Water Treatment', 'Defluoridation', 'Rural'],
  },
  {
    id: 'fa-04',
    sector: 'Farmhouses & Agricultural',
    sectorId: 'farmhouses-agricultural',
    title: 'Transfer Pump for Farm Pond to Storage Tank',
    client: 'Floriculture farm, Pune outskirts',
    challenge: 'Manual pumping from farm pond to overhead tank taking 4 hours daily of labour.',
    solution: 'Installed a Wilo submersible transfer pump with auto float-switch and timer control.',
    result: 'Tank filling fully automated; 4 labour-hours per day reclaimed for productive farm work.',
    brands: ['Wilo'],
    tags: ['Pumping', 'Agricultural', 'Automation'],
  },
];
